#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:mikebarkmin/dotfiles.git"

if command -v nvim >/dev/null 2>&1; then
  echo "Bootstraping NVim"
  nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi
