#!/bin/bash

# install latest i3 for ubuntu
user = "mbarkmin"

echo "Setup Ubuntu for user $user"

echo "copy xorg files"
cp /home/$user/.yadm/xorg.conf.d/* /usr/share/X11/xorg.conf.d/

echo "upgrade ubuntu"
apt update
apt upgrade

echo "install essentials"
apt install -y rxvt
apt install -y zsh
apt install -y vim-gtk3
add-apt-repository ppa:neovim-ppa/stable -y
apt install -y neovim
apt install -y emacs
apt install -y silversearcher-ag
apt install -y python python3
apt install -y python-pip python3-pip
apt install -y htop
apt install -y exuberant-ctags

echo "install sweets"
add-apt-repository ppa:papirus/papirus
apt install -y papirus-icon-theme
apt install -y libreoffice-style-papirus

# install docker
echo "install docker"
apt remove docker docker-engine docker.io
apt install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
apt install -y docker-ce
groupadd docker
adduser $user docker

echo "install i3-gaps with docker"
git clone https://github.com/mifix/i3-gaps-deb-builder.git /home/$user/Sources/i3-gaps-deb-builder
cd /home/$user/Sources/i3-gaps-deb-builder
make
rm -rf /home/$user/Sources/i3-gaps-deb-builder
apt install -y rofi
apt install -y i3lock-fancy


echo "install virt-manager"
apt install -y virt-manager
groupadd libvirtd
adduser $user libvirtd

echo "install office apps"
apt install -y firefox
apt install -y thunderbird
apt install -y xul-ext-lightning xul-ext-gdata-provider enigmail
add-apt-repository ppa:libreoffice/ppa
apt install -y libreoffice
apt install -y simple-scan
add-apt-repository ppa:nextcloud-devs/client
apt install -y nextcloud-client
apt install -y nextcloud-client-nautilus
add-apt-repository ppa:smathot/cogscinl
apt install -y zotero-standalone
apt install -y zathura

echo "install graphic apps"
apt install -y inkscape
add-apt-repository ppa:otto-kesselgulasch/gimp
apt install -y gimp

echo "install media"
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0DF731E45CE24F27EEEB1450EFDC8610341D9410 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
apt update
apt install -y spotify-client
apt install -y vlc

echo "install utils"
apt install -y graphviz
apt install -y virtualenv
apt install -y virtualenvwrapper
apt install -y policykit-1-gnome
apt install -y xbacklight
apt install -y nitrogen
apt install -y lxappearance
apt install -y flameshot
apt install -y redshift redshift-gtk
apt install -y gir1.2-gconf-2.0
apt install -y compton
apt install -y hsetroot

echo "create directories"
mkdir /home/$user/Sources
chown -R $user /home/$user/Sources

echo "install platformio"
python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/develop/scripts/get-platformio.py)"

echo "install r"
apt install r-base
apt install libxml2-dev
apt install libcurl4-openssl-dev
apt install libssl-dev

echo "install yarn und packages"
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
apt update
apt install -y yarn
curl -L https://www.npmjs.com/install.sh | sh
apt install -y npm

echo "install python packages"
pip install neovim
pip3 install neovim
pip  install autopep8 isort yapf
pip3 install autopep8 isort yapf
pip3 install virtualenvwrapper

echo "install language-servers"
npm i -g javascript-typescript-langserver
pip install 'python-language-server[all]'

ln -s /etc/profile.d/vte-*.sh /etc/profile.d/vte.sh
