#!/bin/bash

# install latest i3 for ubuntu
user = "mbarkmin"

echo "Setup Ubuntu for user $user"

echo "copy xorg files"
cp /home/$user/.yadm/xorg.conf.d/* /usr/share/X11/xorg.conf.d/

echo "upgrade ubuntu"
apt update
apt upgrade

echo "install essentials"
apt install -y zsh
apt install -y vim-gtk3
apt install -y emacs

echo "install i3"
/usr/lib/apt/apt-helper download-file http://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2018.01.30_all.deb keyring.deb SHA256:baa43dbbd7232ea2b5444cae238d53bebb9d34601cc000e82f11111b1889078a
dpkg -i ./keyring.deb
echo "deb http://debian.sur5r.net/i3/ $(grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=) universe" >> /etc/apt/sources.list.d/sur5r-i3.list
rm -rf ./keyring.deb
apt update
apt install -y i3
apt install -y rofi
apt install -y i3lock-fancy

# install docker
echo "install docker"
apt remove docker docker-engine docker.io
apt install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
apt install -y docker-ce
groupadd docker
adduser $user docker

echo "install virt-manager"
apt install -y virt-manager
groupadd libvirtd
adduser $user libvirtd

echo "install office apps"
apt install -y firefox
apt install -y thunderbird
apt install -y xul-ext-lightning xul-ext-gdata-provider enigmail
add-apt-repository ppa:libreoffice/ppa
apt install -y libreoffice
apt install -y simple-scan
add-apt-repository ppa:nextcloud-devs/client
apt install -y nextcloud-client
apt install -y nextcloud-client-nautilus
add-apt-repository ppa:smathot/cogscinl
apt install -y zotero-standalone
apt install -y zathura

echo "install graphic apps"
apt install -y inkscape
add-apt-repository ppa:otto-kesselgulasch/gimp
apt install -y gimp

echo "install media"
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0DF731E45CE24F27EEEB1450EFDC8610341D9410 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
apt update
apt install -y spotify-client
apt install -y vlc

echo "install utils"
apt install -y policykit-1-gnome
apt install -y xbacklight

echo "create directories"
mkdir /home/$user/Sources
chown -R $user /home/$user/Sources

echo "install platformio"
python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/develop/scripts/get-platformio.py)"
